language: node_js

node_js:
  - "10.12.0"

script:
  - echo "Deploy test"

install:
  - npm install -g firebase-tools
  - cd functions && npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
