language: node_js

node_js:
  - "10.12.0"

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "hanatalk-cdddb"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
